@extends('layouts.app')
@section('title', __('app.auth.login_title'))
@push('head')<style>.auth-shell{min-height:100vh;display:grid;grid-template-columns:1.05fr .95fr}.auth-showcase{position:relative;overflow:hidden;display:flex;align-items:center;padding:8%;color:#fff;background:linear-gradient(145deg,#075d45 0%,#087f5b 45%,#3268d7 100%)}.auth-showcase:after{content:"";position:absolute;width:420px;height:420px;border:70px solid rgba(255,255,255,.08);border-radius:50%;inset:auto -140px -150px auto}.auth-copy{position:relative;z-index:1;max-width:560px}.auth-form-side{display:flex;align-items:center;justify-content:center;padding:32px}.auth-card{width:100%;max-width:460px}.auth-icon{width:52px;height:52px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,#e5f4ff,#e9e3ff);color:#3268d7;font-size:1.3rem}@media(max-width:900px){.auth-shell{grid-template-columns:1fr}.auth-showcase{display:none}.auth-form-side{padding:20px}}</style>@endpush
@section('content')
<div class="position-absolute top-0 end-0 p-3 z-3">@include('layouts.language-switcher')</div>
<div class="auth-shell"><section class="auth-showcase"><div class="auth-copy"><div class="brand-mark mb-4"><i class="bi bi-buildings fs-4"></i></div><span class="eyebrow text-white opacity-75">{{ __('app.brand.name') }}</span><h1 class="display-5 fw-bold mt-2 mb-3">{{ __('app.auth.welcome') }}</h1><p class="lead opacity-75">{{ __('app.auth.intro') }}</p><div class="d-grid gap-3 mt-5"><div><i class="bi bi-check-circle-fill me-2"></i>{{ __('app.auth.feature_1') }}</div><div><i class="bi bi-shield-check me-2"></i>{{ __('app.auth.feature_2') }}</div></div></div></section>
<section class="auth-form-side"><div class="auth-card"><div class="auth-icon mb-4"><i class="bi bi-person-lock"></i></div><h2 class="page-title h2 mb-1">{{ __('app.auth.login_title') }}</h2><p class="text-secondary mb-4">{{ __('app.auth.login_subtitle') }}</p>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('login.attempt') }}">@csrf
<div class="mb-3"><label class="form-label">{{ __('app.auth.email') }}</label><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-envelope"></i></span><input class="form-control border-start-0" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="email"></div></div>
<div class="mb-3"><label class="form-label">{{ __('app.auth.password') }}</label><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-lock"></i></span><input class="form-control border-start-0" type="password" name="password" required autocomplete="current-password"></div></div>
<div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="remember" id="remember"><label class="form-check-label" for="remember">{{ __('app.auth.remember') }}</label></div>
<button class="btn btn-primary w-100">{{ __('app.auth.login') }} <i class="bi bi-arrow-right ms-1"></i></button></form>
<div class="text-center mt-4">{{ __('app.auth.no_account') }} <a class="fw-bold" href="{{ route('register') }}">{{ __('app.auth.register') }}</a></div><div class="small text-secondary text-center mt-3">{{ __('app.auth.demo') }}</div></div></section></div>
@endsection
