@extends('layouts.app')
@section('title', __('app.nav.dashboard'))
@push('head')<style>.welcome-panel{position:relative;overflow:hidden;min-height:185px;padding:30px;color:#fff;background:linear-gradient(125deg,#075d45,#087f5b 48%,#3268d7)}.welcome-panel:after{content:"";position:absolute;width:260px;height:260px;inset:-105px -55px auto auto;border-radius:50%;border:48px solid rgba(255,255,255,.08)}[dir=rtl] .welcome-panel:after{inset:-105px auto auto -55px}.welcome-content{position:relative;z-index:1;max-width:650px}.stat-card{padding:20px;height:100%}.stat-icon{width:47px;height:47px;display:grid;place-items:center;border-radius:14px;font-size:1.18rem}.stat-value{font-size:1.8rem;font-weight:800}.quick-action{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid var(--border);border-radius:14px;color:var(--ink)}.quick-action:hover{background:#f5fcf9}</style>@endpush
@section('content')
<div class="card welcome-panel mb-4"><div class="welcome-content"><div class="eyebrow text-white opacity-75 mb-2">{{ __('app.dashboard.hello',['name'=>explode(' ',auth()->user()->name)[0]]) }}</div><h1 class="page-title display-6 mb-2">{{ __('app.dashboard.title') }}</h1><p class="mb-4 opacity-75">{{ __('app.dashboard.subtitle') }}</p><a class="btn btn-light text-success" href="{{ route('requests.create') }}"><i class="bi bi-plus-lg me-1"></i>{{ __('app.dashboard.create_request') }}</a></div></div>
<div class="d-flex justify-content-between align-items-end mb-3"><div><span class="eyebrow">{{ __('app.dashboard.key_metrics') }}</span><h2 class="h4 page-title mb-0">{{ __('app.dashboard.activity_overview') }}</h2></div><span class="text-secondary small d-none d-md-inline">{{ __('app.dashboard.realtime') }}</span></div>
<div class="row g-3 mb-4">@foreach([[__('app.citizens.title'),$citizenCount,'bi-people-fill','#e5f4ff','#1677a8'],[__('app.nav.requests'),$requestCount,'bi-file-earmark-text-fill','#e6f5ef','#087f5b'],[__('app.dashboard.active_employees'),$employeeCount,'bi-person-badge-fill','#fff3df','#bf7311'],[__('app.dashboard.active_services'),$serviceCount,'bi-diagram-3-fill','#f0eaff','#7451bd']] as [$label,$value,$icon,$bg,$color])<div class="col-6 col-xl-3"><div class="card stat-card"><span class="stat-icon mb-3" style="background:{{ $bg }};color:{{ $color }}"><i class="bi {{ $icon }}"></i></span><div class="stat-value">{{ $value }}</div><div class="text-secondary small">{{ $label }}</div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-5"><div class="card p-4 h-100"><span class="eyebrow">{{ __('app.dashboard.distribution') }}</span><h2 class="h5 page-title">{{ __('app.dashboard.request_status') }}</h2><div style="height:280px"><canvas id="statusChart"></canvas></div></div></div><div class="col-xl-7"><div class="card h-100"><div class="d-flex justify-content-between p-4 pb-2"><div><span class="eyebrow">{{ __('app.dashboard.recent_activity') }}</span><h2 class="h5 page-title">{{ __('app.dashboard.latest_requests') }}</h2></div><a href="{{ route('requests.index') }}">{{ __('app.dashboard.view_all') }}</a></div><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('app.requests.reference') }}</th><th>{{ __('app.requests.citizen') }}</th><th>{{ __('app.common.state') }}</th></tr></thead><tbody>@forelse($recentRequests as $item)<tr><td><a href="{{ route('requests.show',$item) }}">{{ $item->reference }}</a></td><td>{{ $item->citizen->full_name }}</td><td><span class="badge text-bg-secondary">{{ __('app.status.'.$item->status) }}</span></td></tr>@empty<tr><td colspan="3">{{ __('app.requests.none') }}</td></tr>@endforelse</tbody></table></div></div></div></div>
<div class="card p-4 mt-4"><span class="eyebrow">{{ __('app.dashboard.quick_access') }}</span><h2 class="h5 page-title mb-3">{{ __('app.dashboard.frequent_actions') }}</h2><div class="row g-3"><div class="col-md-4"><a class="quick-action" href="{{ route('citizens.create') }}"><span class="stat-icon" style="background:#e5f4ff;color:#1677a8"><i class="bi bi-person-plus-fill"></i></span><span><strong>{{ __('app.dashboard.new_citizen') }}</strong><small class="d-block text-secondary">{{ __('app.dashboard.new_citizen_help') }}</small></span></a></div><div class="col-md-4"><a class="quick-action" href="{{ route('requests.create') }}"><span class="stat-icon" style="background:#e6f5ef;color:#087f5b"><i class="bi bi-file-earmark-plus-fill"></i></span><span><strong>{{ __('app.dashboard.new_request') }}</strong><small class="d-block text-secondary">{{ __('app.dashboard.new_request_help') }}</small></span></a></div><div class="col-md-4"><a class="quick-action" href="{{ route('notifications.index') }}"><span class="stat-icon" style="background:#fff3df;color:#bf7311"><i class="bi bi-bell-fill"></i></span><span><strong>{{ __('app.nav.notifications') }}</strong><small class="d-block text-secondary">{{ __('app.dashboard.notifications_help') }}</small></span></a></div></div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"></script><script>new Chart(document.getElementById('statusChart'),{type:'doughnut',data:{labels:@json(array_values(\App\Models\AdministrativeRequest::statusLabels())),datasets:[{data:@json(array_map(fn($s)=>(int)($statusCounts[$s]??0),array_keys(\App\Models\AdministrativeRequest::STATUSES))),backgroundColor:['#efb84d','#3b82f6','#14a875','#ef6464'],borderWidth:0}]},options:{maintainAspectRatio:false,cutout:'72%',plugins:{legend:{position:'bottom'}}}})</script>@endpush
