<?php

return [
    'brand' => ['name' => 'Ahfir Municipality', 'subtitle' => 'Digital administration'],
    'language' => ['label' => 'Language', 'fr' => 'Français', 'en' => 'English', 'ar' => 'العربية'],
    'nav' => ['overview' => 'Overview', 'management' => 'Management', 'administration' => 'Administration', 'dashboard' => 'Dashboard', 'citizens' => 'Citizens', 'requests' => 'Requests', 'notifications' => 'Notifications', 'employees' => 'Employees', 'services' => 'Services', 'roles' => 'Roles & access', 'portal' => 'Internal portal', 'logout' => 'Log out'],
    'auth' => ['welcome' => 'Welcome to the municipal portal', 'intro' => 'A modern platform to manage services, track requests and better serve citizens.', 'feature_1' => 'Centralized request tracking', 'feature_2' => 'Secure, multilingual management', 'login_title' => 'Secure login', 'register_title' => 'Create an account', 'login_subtitle' => 'Access your workspace', 'register_subtitle' => 'Join the administrative portal', 'name' => 'Full name', 'email' => 'Email address', 'password' => 'Password', 'password_confirmation' => 'Confirm password', 'remember' => 'Remember me', 'login' => 'Sign in', 'register' => 'Create my account', 'no_account' => 'No account yet?', 'already_account' => 'Already have an account?', 'invalid_credentials' => 'Invalid credentials.', 'account_created' => 'Your account was created successfully.', 'demo' => 'Demo account: admin@ahfir.ma / password'],
    'common' => ['add' => 'Add', 'create' => 'Create', 'save' => 'Save', 'cancel' => 'Cancel', 'edit' => 'Edit', 'delete' => 'Delete', 'view' => 'View', 'all' => 'All', 'active' => 'Active', 'inactive' => 'Inactive', 'yes' => 'Yes', 'no' => 'No', 'none' => 'None', 'unassigned' => 'Unassigned', 'actions' => 'Actions', 'state' => 'Status', 'date' => 'Date', 'code' => 'Code', 'name' => 'Name', 'description' => 'Description', 'email' => 'Email', 'phone' => 'Phone', 'address' => 'Address', 'confirm_delete' => 'Confirm deletion?', 'fix_errors' => 'Please correct the errors.', 'no_data' => 'No data available.'],
    'dashboard' => ['hello' => 'Hello, :name', 'title' => 'Manage municipal services.', 'subtitle' => 'Track cases, coordinate teams and improve the citizen experience from one place.', 'create_request' => 'Create request', 'key_metrics' => 'Key metrics', 'activity_overview' => 'Activity overview', 'realtime' => 'Real-time data', 'active_employees' => 'Active employees', 'active_services' => 'Active services', 'distribution' => 'Distribution', 'request_status' => 'Request status', 'total' => ':count total', 'recent_activity' => 'Recent activity', 'latest_requests' => 'Latest requests', 'view_all' => 'View all', 'quick_access' => 'Quick access', 'frequent_actions' => 'Frequent actions', 'new_citizen' => 'New citizen', 'new_citizen_help' => 'Create a citizen record', 'new_request' => 'New request', 'new_request_help' => 'Register a case', 'notifications_help' => 'Review communications'],
    'status' => ['pending' => 'Pending', 'processing' => 'Processing', 'approved' => 'Approved', 'rejected' => 'Rejected'],
    'citizens' => ['title' => 'Citizens', 'singular' => 'Citizen', 'add' => 'Add citizen', 'edit' => 'Edit citizen', 'cin' => 'National ID', 'first_name' => 'First name', 'last_name' => 'Last name', 'full_name' => 'Full name', 'birth_date' => 'Birth date', 'contact' => 'Contact', 'requests' => 'Requests', 'details' => 'Contact details', 'none' => 'No citizens.'],
    'requests' => ['title' => 'Administrative requests', 'singular' => 'Request', 'new' => 'New request', 'edit' => 'Edit request', 'reference' => 'Reference', 'type' => 'Request type', 'service' => 'Service', 'citizen' => 'Citizen', 'employee' => 'Assigned agent', 'all_statuses' => 'All statuses', 'admin_notes' => 'Internal notes', 'submitted_at' => 'Submitted', 'none' => 'No requests.', 'sent_notifications' => 'Sent notifications', 'delete_confirm' => 'Delete this request?'],
    'employees' => ['title' => 'Employees', 'add' => 'Add employee', 'edit' => 'Edit employee', 'number' => 'Employee ID', 'position' => 'Position', 'service' => 'Service', 'hire_date' => 'Hire date', 'active' => 'Active employee'],
    'services' => ['title' => 'Municipal services', 'add' => 'Add service', 'edit' => 'Edit service', 'active' => 'Active service'],
    'roles' => ['title' => 'Role management', 'user' => 'User', 'role' => 'Role', 'admin' => 'Administrator', 'agent' => 'Agent'],
    'notifications' => ['title' => 'Citizen notifications', 'notification' => 'Notification', 'read' => 'Read', 'mark_read' => 'Mark read', 'none' => 'No notifications.', 'request_updated' => 'Your request was updated', 'request_status_message' => 'Request :reference is now: :status.'],
    'flash' => ['citizen_has_requests' => 'This citizen cannot be deleted because they have requests.', 'service_in_use' => 'This service cannot be deleted because it is in use.', 'self_role' => 'You cannot remove your own administrator role.', 'citizen_added' => 'Citizen added.', 'citizen_updated' => 'Citizen updated.', 'citizen_deleted' => 'Citizen deleted.', 'request_added' => 'Request registered.', 'request_updated' => 'Request updated.', 'request_deleted' => 'Request deleted.', 'service_added' => 'Service added.', 'service_updated' => 'Service updated.', 'service_deleted' => 'Service deleted.', 'employee_added' => 'Employee added.', 'employee_updated' => 'Employee updated.', 'employee_deleted' => 'Employee deleted.', 'role_updated' => 'Role updated.', 'notification_read' => 'Notification marked as read.'],
];
