<?php

return [
    'brand' => ['name' => 'Commune d’Ahfir', 'subtitle' => 'Administration digitale'],
    'language' => ['label' => 'Langue', 'fr' => 'Français', 'en' => 'English', 'ar' => 'العربية'],
    'nav' => ['overview' => 'Vue générale', 'management' => 'Gestion', 'administration' => 'Administration', 'dashboard' => 'Tableau de bord', 'citizens' => 'Citoyens', 'requests' => 'Demandes', 'notifications' => 'Notifications', 'employees' => 'Employés', 'services' => 'Services', 'roles' => 'Rôles & accès', 'portal' => 'Portail interne', 'logout' => 'Déconnexion'],
    'auth' => ['welcome' => 'Bienvenue sur le portail communal', 'intro' => 'Une plateforme moderne pour déposer, suivre et résoudre les réclamations des citoyens.', 'feature_1' => 'Suivi centralisé des réclamations', 'feature_2' => 'Gestion sécurisée et multilingue', 'login_title' => 'Connexion sécurisée', 'register_title' => 'Créer un compte', 'login_subtitle' => 'Accédez à votre espace de travail', 'register_subtitle' => 'Rejoignez le portail administratif', 'name' => 'Nom complet', 'email' => 'Adresse e-mail', 'password' => 'Mot de passe', 'password_confirmation' => 'Confirmer le mot de passe', 'remember' => 'Se souvenir de moi', 'login' => 'Se connecter', 'register' => 'Créer mon compte', 'no_account' => 'Pas encore de compte ?', 'already_account' => 'Vous avez déjà un compte ?', 'invalid_credentials' => 'Identifiants incorrects.', 'account_created' => 'Votre compte a été créé avec succès.', 'demo' => 'Compte démo : admin@ahfir.ma / password'],
    'common' => ['add' => 'Ajouter', 'create' => 'Créer', 'save' => 'Enregistrer', 'cancel' => 'Annuler', 'edit' => 'Modifier', 'delete' => 'Supprimer', 'view' => 'Voir', 'all' => 'Tous', 'active' => 'Actif', 'inactive' => 'Inactif', 'yes' => 'Oui', 'no' => 'Non', 'none' => 'Aucun', 'unassigned' => 'Non assigné', 'actions' => 'Actions', 'state' => 'État', 'date' => 'Date', 'code' => 'Code', 'name' => 'Nom', 'description' => 'Description', 'email' => 'E-mail', 'phone' => 'Téléphone', 'address' => 'Adresse', 'confirm_delete' => 'Confirmer la suppression ?', 'fix_errors' => 'Veuillez corriger les erreurs.', 'no_data' => 'Aucune donnée disponible.'],
    'dashboard' => ['hello' => 'Bonjour, :name', 'title' => 'Pilotez les services de la commune.', 'subtitle' => 'Suivez les dossiers, coordonnez les équipes et améliorez l’expérience citoyenne depuis un espace unique.', 'create_request' => 'Créer une demande', 'key_metrics' => 'Indicateurs clés', 'activity_overview' => 'Aperçu de l’activité', 'realtime' => 'Données en temps réel', 'active_employees' => 'Employés actifs', 'active_services' => 'Services actifs', 'distribution' => 'Répartition', 'request_status' => 'État des demandes', 'total' => ':count total', 'recent_activity' => 'Activité récente', 'latest_requests' => 'Dernières demandes', 'view_all' => 'Tout voir', 'quick_access' => 'Accès rapide', 'frequent_actions' => 'Actions fréquentes', 'new_citizen' => 'Nouveau citoyen', 'new_citizen_help' => 'Créer une fiche citoyenne', 'new_request' => 'Nouvelle demande', 'new_request_help' => 'Enregistrer un dossier', 'notifications_help' => 'Consulter les communications'],
    'status' => ['pending' => 'En attente', 'processing' => 'En cours', 'approved' => 'Validée', 'rejected' => 'Refusée'],
    'citizens' => ['title' => 'Citoyens', 'singular' => 'Citoyen', 'add' => 'Ajouter un citoyen', 'edit' => 'Modifier le citoyen', 'cin' => 'CIN', 'first_name' => 'Prénom', 'last_name' => 'Nom', 'full_name' => 'Nom complet', 'birth_date' => 'Date de naissance', 'contact' => 'Contact', 'requests' => 'Demandes', 'details' => 'Coordonnées', 'none' => 'Aucun citoyen.'],
    'requests' => ['title' => 'Demandes administratives', 'singular' => 'Demande', 'new' => 'Nouvelle demande', 'edit' => 'Modifier la demande', 'reference' => 'Référence', 'type' => 'Type de demande', 'service' => 'Service', 'citizen' => 'Citoyen', 'employee' => 'Agent assigné', 'all_statuses' => 'Tous les états', 'admin_notes' => 'Notes internes', 'submitted_at' => 'Dépôt', 'none' => 'Aucune demande.', 'sent_notifications' => 'Notifications envoyées', 'delete_confirm' => 'Supprimer cette demande ?'],
    'employees' => ['title' => 'Employés', 'add' => 'Ajouter un employé', 'edit' => 'Modifier l’employé', 'number' => 'Matricule', 'position' => 'Fonction', 'service' => 'Service', 'hire_date' => 'Date d’embauche', 'active' => 'Employé actif'],
    'services' => ['title' => 'Services communaux', 'add' => 'Ajouter un service', 'edit' => 'Modifier le service', 'active' => 'Service actif'],
    'roles' => ['title' => 'Gestion des rôles', 'user' => 'Utilisateur', 'role' => 'Rôle', 'admin' => 'Administrateur', 'employee' => 'Employé', 'citizen' => 'Citoyen'],
    'notifications' => ['title' => 'Notifications citoyennes', 'notification' => 'Notification', 'read' => 'Lue', 'mark_read' => 'Marquer lue', 'none' => 'Aucune notification.', 'request_updated' => 'Mise à jour de votre demande', 'request_status_message' => 'La demande :reference est maintenant : :status.'],
    'flash' => ['citizen_has_requests' => 'Suppression impossible : ce citoyen possède des demandes.', 'service_in_use' => 'Suppression impossible : ce service est utilisé.', 'self_role' => 'Vous ne pouvez pas retirer votre propre rôle administrateur.', 'citizen_added' => 'Citoyen ajouté.', 'citizen_updated' => 'Citoyen modifié.', 'citizen_deleted' => 'Citoyen supprimé.', 'request_added' => 'Demande enregistrée.', 'request_updated' => 'Demande modifiée.', 'request_deleted' => 'Demande supprimée.', 'service_added' => 'Service ajouté.', 'service_updated' => 'Service modifié.', 'service_deleted' => 'Service supprimé.', 'employee_added' => 'Employé ajouté.', 'employee_updated' => 'Employé modifié.', 'employee_deleted' => 'Employé supprimé.', 'role_updated' => 'Rôle mis à jour.', 'notification_read' => 'Notification marquée comme lue.'],
];
