<?php

return [
    'brand' => ['name' => 'جماعة أحفير', 'subtitle' => 'الإدارة الرقمية'],
    'language' => ['label' => 'اللغة', 'fr' => 'Français', 'en' => 'English', 'ar' => 'العربية'],
    'nav' => ['overview' => 'نظرة عامة', 'management' => 'التدبير', 'administration' => 'الإدارة', 'dashboard' => 'لوحة القيادة', 'citizens' => 'المواطنون', 'requests' => 'الطلبات', 'notifications' => 'الإشعارات', 'employees' => 'الموظفون', 'services' => 'المصالح', 'roles' => 'الأدوار والصلاحيات', 'portal' => 'البوابة الداخلية', 'logout' => 'تسجيل الخروج'],
    'auth' => ['welcome' => 'مرحباً بكم في البوابة الجماعية', 'intro' => 'منصة حديثة لتدبير المصالح وتتبع الطلبات وخدمة المواطنين بشكل أفضل.', 'feature_1' => 'تتبع مركزي للطلبات', 'feature_2' => 'تدبير آمن ومتعدد اللغات', 'login_title' => 'تسجيل دخول آمن', 'register_title' => 'إنشاء حساب', 'login_subtitle' => 'الدخول إلى فضاء العمل', 'register_subtitle' => 'الانضمام إلى البوابة الإدارية', 'name' => 'الاسم الكامل', 'email' => 'البريد الإلكتروني', 'password' => 'كلمة المرور', 'password_confirmation' => 'تأكيد كلمة المرور', 'remember' => 'تذكرني', 'login' => 'تسجيل الدخول', 'register' => 'إنشاء حسابي', 'no_account' => 'ليس لديك حساب؟', 'already_account' => 'لديك حساب بالفعل؟', 'invalid_credentials' => 'بيانات الدخول غير صحيحة.', 'account_created' => 'تم إنشاء حسابك بنجاح.', 'demo' => 'حساب تجريبي: admin@ahfir.ma / password'],
    'common' => ['add' => 'إضافة', 'create' => 'إنشاء', 'save' => 'حفظ', 'cancel' => 'إلغاء', 'edit' => 'تعديل', 'delete' => 'حذف', 'view' => 'عرض', 'all' => 'الكل', 'active' => 'نشط', 'inactive' => 'غير نشط', 'yes' => 'نعم', 'no' => 'لا', 'none' => 'لا يوجد', 'unassigned' => 'غير مسند', 'actions' => 'الإجراءات', 'state' => 'الحالة', 'date' => 'التاريخ', 'code' => 'الرمز', 'name' => 'الاسم', 'description' => 'الوصف', 'email' => 'البريد الإلكتروني', 'phone' => 'الهاتف', 'address' => 'العنوان', 'confirm_delete' => 'تأكيد الحذف؟', 'fix_errors' => 'يرجى تصحيح الأخطاء.', 'no_data' => 'لا توجد بيانات.'],
    'dashboard' => ['hello' => 'مرحباً، :name', 'title' => 'دبّر مصالح الجماعة بفعالية.', 'subtitle' => 'تتبع الملفات ونسق الفرق وحسّن تجربة المواطن من فضاء موحد.', 'create_request' => 'إنشاء طلب', 'key_metrics' => 'المؤشرات الرئيسية', 'activity_overview' => 'نظرة عامة على النشاط', 'realtime' => 'بيانات آنية', 'active_employees' => 'الموظفون النشطون', 'active_services' => 'المصالح النشطة', 'distribution' => 'التوزيع', 'request_status' => 'حالة الطلبات', 'total' => 'المجموع :count', 'recent_activity' => 'النشاط الأخير', 'latest_requests' => 'أحدث الطلبات', 'view_all' => 'عرض الكل', 'quick_access' => 'ولوج سريع', 'frequent_actions' => 'الإجراءات المتكررة', 'new_citizen' => 'مواطن جديد', 'new_citizen_help' => 'إنشاء ملف مواطن', 'new_request' => 'طلب جديد', 'new_request_help' => 'تسجيل ملف', 'notifications_help' => 'مراجعة المراسلات'],
    'status' => ['pending' => 'قيد الانتظار', 'processing' => 'قيد المعالجة', 'approved' => 'مقبول', 'rejected' => 'مرفوض'],
    'citizens' => ['title' => 'المواطنون', 'singular' => 'المواطن', 'add' => 'إضافة مواطن', 'edit' => 'تعديل المواطن', 'cin' => 'رقم البطاقة الوطنية', 'first_name' => 'الاسم الشخصي', 'last_name' => 'الاسم العائلي', 'full_name' => 'الاسم الكامل', 'birth_date' => 'تاريخ الميلاد', 'contact' => 'التواصل', 'requests' => 'الطلبات', 'details' => 'معلومات التواصل', 'none' => 'لا يوجد مواطنون.'],
    'requests' => ['title' => 'الطلبات الإدارية', 'singular' => 'الطلب', 'new' => 'طلب جديد', 'edit' => 'تعديل الطلب', 'reference' => 'المرجع', 'type' => 'نوع الطلب', 'service' => 'المصلحة', 'citizen' => 'المواطن', 'employee' => 'الموظف المكلف', 'all_statuses' => 'جميع الحالات', 'admin_notes' => 'ملاحظات داخلية', 'submitted_at' => 'تاريخ الإيداع', 'none' => 'لا توجد طلبات.', 'sent_notifications' => 'الإشعارات المرسلة', 'delete_confirm' => 'حذف هذا الطلب؟'],
    'employees' => ['title' => 'الموظفون', 'add' => 'إضافة موظف', 'edit' => 'تعديل الموظف', 'number' => 'رقم التأجير', 'position' => 'المهمة', 'service' => 'المصلحة', 'hire_date' => 'تاريخ التوظيف', 'active' => 'موظف نشط'],
    'services' => ['title' => 'المصالح الجماعية', 'add' => 'إضافة مصلحة', 'edit' => 'تعديل المصلحة', 'active' => 'مصلحة نشطة'],
    'roles' => ['title' => 'تدبير الأدوار', 'user' => 'المستخدم', 'role' => 'الدور', 'admin' => 'مدير', 'agent' => 'موظف'],
    'notifications' => ['title' => 'إشعارات المواطنين', 'notification' => 'الإشعار', 'read' => 'مقروء', 'mark_read' => 'تحديد كمقروء', 'none' => 'لا توجد إشعارات.', 'request_updated' => 'تم تحديث طلبكم', 'request_status_message' => 'أصبح الطلب :reference الآن: :status.'],
    'flash' => ['citizen_has_requests' => 'لا يمكن حذف هذا المواطن لوجود طلبات مرتبطة به.', 'service_in_use' => 'لا يمكن حذف هذه المصلحة لأنها مستخدمة.', 'self_role' => 'لا يمكنك إزالة دور المدير من حسابك.', 'citizen_added' => 'تمت إضافة المواطن.', 'citizen_updated' => 'تم تعديل المواطن.', 'citizen_deleted' => 'تم حذف المواطن.', 'request_added' => 'تم تسجيل الطلب.', 'request_updated' => 'تم تعديل الطلب.', 'request_deleted' => 'تم حذف الطلب.', 'service_added' => 'تمت إضافة المصلحة.', 'service_updated' => 'تم تعديل المصلحة.', 'service_deleted' => 'تم حذف المصلحة.', 'employee_added' => 'تمت إضافة الموظف.', 'employee_updated' => 'تم تعديل الموظف.', 'employee_deleted' => 'تم حذف الموظف.', 'role_updated' => 'تم تحديث الدور.', 'notification_read' => 'تم تحديد الإشعار كمقروء.'],
];
