<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', __('app.brand.name'))</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&family=Noto+Kufi+Arabic:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap{{ app()->getLocale() === 'ar' ? '.rtl' : '' }}.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root { --primary:#087f5b;--primary-dark:#075d45;--blue:#3268d7;--violet:#7654c8;--amber:#d68b18;--ink:#17251f;--muted:#718078;--canvas:#f3f7f5;--border:#e3ebe7;--sidebar-width:270px; }
        *{box-sizing:border-box} body{margin:0;background:var(--canvas);color:var(--ink);font-family:"DM Sans",sans-serif} [dir=rtl] body{font-family:"Noto Kufi Arabic",sans-serif} h1,h2,h3,h4,h5,h6,.brand-name{font-family:"Manrope",sans-serif}[dir=rtl] h1,[dir=rtl] h2,[dir=rtl] h3,[dir=rtl] h4,[dir=rtl] h5,[dir=rtl] h6,[dir=rtl] .brand-name{font-family:"Noto Kufi Arabic",sans-serif}a{color:var(--primary);text-decoration:none}
        .sidebar{position:fixed;inset:0 auto 0 0;z-index:1035;width:var(--sidebar-width);display:flex;flex-direction:column;padding:24px 18px;background:linear-gradient(170deg,#063f31 0%,#075d45 55%,#087f5b 100%);color:#fff;overflow-y:auto}[dir=rtl] .sidebar{inset:0 0 0 auto}
        .brand{display:flex;align-items:center;gap:12px;color:#fff;padding:0 8px 25px}.brand:hover{color:#fff}.brand-mark{width:46px;height:46px;display:grid;place-items:center;flex:0 0 auto;border-radius:15px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.2)}.brand-name{display:block;font-size:1rem;font-weight:800}.brand-subtitle{display:block;color:rgba(255,255,255,.58);font-size:.72rem}
        .nav-label{padding:16px 13px 7px;color:rgba(255,255,255,.42);font-size:.65rem;font-weight:700;letter-spacing:.13em;text-transform:uppercase}.sidebar-nav{display:grid;gap:5px}.sidebar-link{display:flex;align-items:center;gap:12px;padding:11px 13px;border-radius:12px;color:rgba(255,255,255,.72);font-weight:500;transition:.2s}.sidebar-link i{width:20px}.sidebar-link:hover{color:#fff;background:rgba(255,255,255,.08)}.sidebar-link.active{color:#fff;background:rgba(255,255,255,.15);box-shadow:inset 3px 0 #7ef0bd,0 8px 20px rgba(0,0,0,.12)}[dir=rtl] .sidebar-link.active{box-shadow:inset -3px 0 #7ef0bd,0 8px 20px rgba(0,0,0,.12)}
        .sidebar-footer{margin-top:auto;padding-top:24px}.user-panel{padding:13px;border-radius:15px;background:rgba(0,0,0,.14);border:1px solid rgba(255,255,255,.1)}.user-avatar{width:38px;height:38px;display:grid;place-items:center;border-radius:12px;background:#fff;color:var(--primary);font-weight:800}.logout-btn{color:rgba(255,255,255,.65);border:0;background:transparent}
        .main-area{min-height:100vh;margin-left:var(--sidebar-width)}[dir=rtl] .main-area{margin-left:0;margin-right:var(--sidebar-width)}.topbar{height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 34px;background:rgba(255,255,255,.84);border-bottom:1px solid var(--border);backdrop-filter:blur(18px);position:sticky;top:0;z-index:1020}.content-wrap{padding:32px 34px 50px;max-width:1600px;margin:auto}.page-title{font-weight:800;letter-spacing:-.035em}.eyebrow{color:var(--primary);font-size:.72rem;font-weight:800;letter-spacing:.11em;text-transform:uppercase}
        .card{border:1px solid rgba(227,235,231,.7);border-radius:20px;box-shadow:0 12px 35px rgba(17,65,48,.065)}.btn{border-radius:11px;font-weight:600;padding:.62rem 1rem}.btn-sm{border-radius:9px;padding:.4rem .68rem}.btn-primary{background:linear-gradient(135deg,var(--primary),#13a276);border:0;box-shadow:0 7px 16px rgba(8,127,91,.18)}.btn-primary:hover{background:linear-gradient(135deg,var(--primary-dark),var(--primary));transform:translateY(-1px)}.form-control,.form-select{min-height:45px;border-color:var(--border);border-radius:11px;background:#fbfdfc}.form-control:focus,.form-select:focus{border-color:#55b897;box-shadow:0 0 0 .22rem rgba(8,127,91,.1)}.form-label{color:#526159;font-size:.84rem;font-weight:600}.table>:not(caption)>*>*{padding:.95rem 1rem;border-bottom-color:var(--border)}.table thead th{color:#829087;font-size:.7rem;font-weight:800;letter-spacing:.07em;text-transform:uppercase;background:#f8fbf9}.table tbody tr:hover{background:#f8fcfa}.badge{border-radius:8px;padding:.45em .68em}.text-bg-secondary{color:#176448!important;background:#dff4eb!important}.alert{border:0;border-radius:14px}.mobile-topbar{display:none}.lang-menu .dropdown-toggle{border:1px solid var(--border);background:#fff}.auth-main{min-height:100vh;background:radial-gradient(circle at 12% 10%,rgba(50,104,215,.16),transparent 27%),radial-gradient(circle at 85% 85%,rgba(118,84,200,.14),transparent 28%),#f4f8f6}
        @media(max-width:991.98px){.sidebar{transform:translateX(-100%);transition:.25s;box-shadow:18px 0 45px rgba(6,63,49,.22)}[dir=rtl] .sidebar{transform:translateX(100%)}.sidebar.show{transform:translateX(0)}.main-area,[dir=rtl] .main-area{margin:0}.topbar{display:none}.mobile-topbar{display:flex;position:sticky;top:0;z-index:1030;align-items:center;justify-content:space-between;height:66px;padding:0 18px;color:#fff;background:var(--primary-dark)}.content-wrap{padding:22px 15px 40px}.sidebar-backdrop{position:fixed;inset:0;z-index:1030;display:none;background:rgba(3,26,20,.48);backdrop-filter:blur(2px)}.sidebar-backdrop.show{display:block}}
    </style>@stack('head')
</head>
<body>
@auth
<div class="app-shell"><aside class="sidebar" id="sidebar">
    <a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark"><i class="bi bi-buildings fs-4"></i></span><span><span class="brand-name">{{ __('app.brand.name') }}</span><span class="brand-subtitle">{{ __('app.brand.subtitle') }}</span></span></a>
    <div class="nav-label">{{ __('app.nav.overview') }}</div><nav class="sidebar-nav"><a class="sidebar-link {{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}"><i class="bi bi-grid-1x2-fill"></i>{{ __('app.nav.dashboard') }}</a></nav>
    <div class="nav-label">{{ __('app.nav.management') }}</div><nav class="sidebar-nav">
        <a class="sidebar-link {{ request()->routeIs('citizens.*')?'active':'' }}" href="{{ route('citizens.index') }}"><i class="bi bi-people-fill"></i>{{ __('app.nav.citizens') }}</a>
        <a class="sidebar-link {{ request()->routeIs('requests.*')?'active':'' }}" href="{{ route('requests.index') }}"><i class="bi bi-file-earmark-text-fill"></i>{{ __('app.nav.requests') }}</a>
        <a class="sidebar-link {{ request()->routeIs('notifications.*')?'active':'' }}" href="{{ route('notifications.index') }}"><i class="bi bi-bell-fill"></i>{{ __('app.nav.notifications') }}</a>
    </nav>
    @if(auth()->user()->role==='admin')<div class="nav-label">{{ __('app.nav.administration') }}</div><nav class="sidebar-nav">
        <a class="sidebar-link {{ request()->routeIs('employees.*')?'active':'' }}" href="{{ route('employees.index') }}"><i class="bi bi-person-badge-fill"></i>{{ __('app.nav.employees') }}</a>
        <a class="sidebar-link {{ request()->routeIs('services.*')?'active':'' }}" href="{{ route('services.index') }}"><i class="bi bi-diagram-3-fill"></i>{{ __('app.nav.services') }}</a>
        <a class="sidebar-link {{ request()->routeIs('users.*')?'active':'' }}" href="{{ route('users.index') }}"><i class="bi bi-shield-lock-fill"></i>{{ __('app.nav.roles') }}</a>
    </nav>@endif
    <div class="sidebar-footer"><div class="user-panel d-flex align-items-center gap-2"><div class="user-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</div><div class="overflow-hidden flex-grow-1"><div class="small fw-bold text-truncate">{{ auth()->user()->name }}</div><div class="small opacity-50">{{ __('app.roles.'.auth()->user()->role) }}</div></div><form method="post" action="{{ route('logout') }}">@csrf<button class="logout-btn" title="{{ __('app.nav.logout') }}"><i class="bi bi-box-arrow-right fs-5"></i></button></form></div></div>
</aside><div class="sidebar-backdrop" id="sidebarBackdrop"></div>
<section class="main-area"><header class="mobile-topbar"><button class="btn text-white p-0" id="menuToggle"><i class="bi bi-list fs-2"></i></button><strong>{{ __('app.brand.name') }}</strong><span class="user-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span></header>
<header class="topbar"><div><span class="eyebrow">{{ __('app.nav.portal') }}</span><div class="text-secondary small">{{ now()->translatedFormat('l d F Y') }}</div></div><div class="d-flex align-items-center gap-2">@include('layouts.language-switcher')<a class="btn btn-light" href="{{ route('notifications.index') }}"><i class="bi bi-bell"></i></a><a class="btn btn-primary" href="{{ route('requests.create') }}"><i class="bi bi-plus-lg me-1"></i>{{ __('app.dashboard.new_request') }}</a></div></header>
<main class="content-wrap">@if(session('success'))<div class="alert alert-success"><i class="bi bi-check-circle-fill me-2"></i>{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><strong>{{ __('app.common.fix_errors') }}</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main></section></div>
@else <main class="auth-main">@yield('content')</main> @endauth
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script><script>const sidebar=document.getElementById('sidebar'),backdrop=document.getElementById('sidebarBackdrop');const toggleSidebar=()=>{sidebar?.classList.toggle('show');backdrop?.classList.toggle('show')};document.getElementById('menuToggle')?.addEventListener('click',toggleSidebar);backdrop?.addEventListener('click',toggleSidebar)</script>@stack('scripts')
</body></html>
